server:
  forward-headers-strategy: framework
  port: 8888
spring:
  cloud:
    config:
      server:
        credhub:
          url: https://credhub.service.cf.internal:8844/
        health:
          enabled: false
  credhub:
    url: https://credhub.service.cf.internal:8844/
    path: "/fallback/url/path"
    oauth2:
      registration-id: uaa
  security:
    oauth2:
      client:
        registration:
          uaa:
            provider: uaa
            client-id: scs_client
            client-secret: dXiBnCD4CNbNCGJyj0duWxdQwI2RNQ
            authorization-grant-type: client_credentials

        provider:
          uaa:
            token-uri: ${uaa.token-uri}

uaa:
  uri: https://uaa.service.cf.internal:8443
  token-uri: ${uaa.uri}/oauth/token
  jwk-set-uri: ${uaa.uri}/token_keys

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"
scs:
  credhub:
    path: "${spring.credhub.path}"
  config-server:
    authorization-uri: ${uaa.uri}
    service-instance-id: ${spring.cloud.appbroker.service-instance-id}


 